Sigdat 2022 v1.0 Update SIGDAT Officers, Past Officers and news items
sigdat-org/sigdat pull request #20
Opened 2022-01-06 05:00 UTC by ptlord

Hi Nitin,

Please take a look of the changes. Let me know if you need we need to make further revisions.

Best,

CY

2022-01-06 16:44 UTC, desilinguist requested changes
Found a few formatting bugs. Please see suggestions.

2022-01-06 16:44 UTC, desilinguist commented on _pages/videos.md
> +- url: https://vimeo.com/search?q=EMNLP+2019
```suggestion
  - url: https://vimeo.com/search?q=EMNLP+2019
```

2022-01-06 16:44 UTC, desilinguist commented on _pages/home.md
> +**December 21, 2021**. Prof. Isabelle Augenstein(http://isabelleaugenstein.github.io/) has been elected as the VP-Elect of SIGDAT 2022.
```suggestion
**December 21, 2021**. Prof. Isabelle Augenstein(http://isabelleaugenstein.github.io/) has been elected as the VP-Elect of SIGDAT 2022. {: .notice--info}
```

2022-01-06 16:44 UTC, desilinguist commented on _pages/home.md
> +November 7, 2019. SIGDAT president Dr. Jian Su gave [an update](/assets/documents/SIGDAT-2019-update.pdf) on SIGDAT during the closing session of EMNLP-IJCNLP 2019.
```suggestion
November 7, 2019. SIGDAT president Dr. Jian Su gave [an update](/assets/documents/SIGDAT-2019-update.pdf) on SIGDAT during the closing session of EMNLP-IJCNLP 2019. {: .notice}
```

2022-01-06 16:44 UTC, desilinguist commented on _pages/organization.md
> +## Officers in 2022:
```suggestion
## Officers in 2022
```

2022-01-07 15:11 UTC, desilinguist commented
Also, in the future, you should be able to submit PRs directly to the original SIGDAT repository without needing to fork. I have added you as a collaborator there with write permissions.

2022-01-07 15:40 UTC, merged

2022-01-07 15:41 UTC, ptlord commented
Thank you @desilinguist

2022-01-07 15:48 UTC, ptlord commented
Hi Nitin,

The icon for EMNLP 2019 video link is not ready yet, right?
I wonder do we also have video archive for EMNLP 2020 and EMNLP 2021?

Best,

CY

From: Nitin ***@***.***>
Sent: Friday, January 7, 2022 11:40 PM
To: ***@***.***>
Cc: Chin-Yew ***@***.***>; ***@***.***>
Subject: Re: [sigdat-org/sigdat] Sigdat 2022 v1.0 Update SIGDAT Officers, Past Officers and news items (PR #20)


Merged #20<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsigdat-org%2Fsigdat%2Fpull%2F20&data=04%7C01%7C%7Cbda56a1daaa04acff32808d9d1f4179e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637771668571405803%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KlTVVxSKvEHTIon26gBJQlNTKpaIQkBEGzIHRg5XBJg%3D&reserved=0> into master.

—
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsigdat-org%2Fsigdat%2Fpull%2F20%23event-5858531232&data=04%7C01%7C%7Cbda56a1daaa04acff32808d9d1f4179e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637771668571405803%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fxsgklQnrtJwkxM8cUkR8Z4C87IMtUvnv2ns%2FYgpOSE%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPEVNVY7HKBA3J6XEJ5FDWLUU4CQNANCNFSM5LLP2MPA&data=04%7C01%7C%7Cbda56a1daaa04acff32808d9d1f4179e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637771668571405803%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sFfXGamraixYgC18VCjvffpx7DUTY%2FQ2xPDYVswCywY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cbda56a1daaa04acff32808d9d1f4179e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637771668571405803%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zHinUjyynubsKWPWEFwNDrKsKD5N2DVcB6bV5dNtHeA%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cbda56a1daaa04acff32808d9d1f4179e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637771668571405803%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DiaPuxPeKsf6NhjK7ZmVx3JzGVOMm4J34993fQdxchs%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-01-07 15:52 UTC, desilinguist commented
The 2019 link already works. I just created the channel.

No idea about 2020 and 2021.
________________________________
From: Chin-Yew Lin ***@***.***>
Sent: Friday, January 7, 2022 10:48:50 AM
To: sigdat-org/sigdat ***@***.***>
Cc: Nitin Madnani ***@***.***>; Mention ***@***.***>
Subject: Re: [sigdat-org/sigdat] Sigdat 2022 v1.0 Update SIGDAT Officers, Past Officers and news items (PR #20)


Hi Nitin,

The icon for EMNLP 2019 video link is not ready yet, right?
I wonder do we also have video archive for EMNLP 2020 and EMNLP 2021?

Best,

CY

From: Nitin ***@***.***>
Sent: Friday, January 7, 2022 11:40 PM
To: ***@***.***>
Cc: Chin-Yew ***@***.***>; ***@***.***>
Subject: Re: [sigdat-org/sigdat] Sigdat 2022 v1.0 Update SIGDAT Officers, Past Officers and news items (PR #20)


Merged #20<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsigdat-org%2Fsigdat%2Fpull%2F20&data=04%7C01%7C%7Cbda56a1daaa04acff32808d9d1f4179e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637771668571405803%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KlTVVxSKvEHTIon26gBJQlNTKpaIQkBEGzIHRg5XBJg%3D&reserved=0> into master.

—
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsigdat-org%2Fsigdat%2Fpull%2F20%23event-5858531232&data=04%7C01%7C%7Cbda56a1daaa04acff32808d9d1f4179e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637771668571405803%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fxsgklQnrtJwkxM8cUkR8Z4C87IMtUvnv2ns%2FYgpOSE%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPEVNVY7HKBA3J6XEJ5FDWLUU4CQNANCNFSM5LLP2MPA&data=04%7C01%7C%7Cbda56a1daaa04acff32808d9d1f4179e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637771668571405803%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sFfXGamraixYgC18VCjvffpx7DUTY%2FQ2xPDYVswCywY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cbda56a1daaa04acff32808d9d1f4179e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637771668571405803%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zHinUjyynubsKWPWEFwNDrKsKD5N2DVcB6bV5dNtHeA%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cbda56a1daaa04acff32808d9d1f4179e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637771668571405803%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DiaPuxPeKsf6NhjK7ZmVx3JzGVOMm4J34993fQdxchs%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>


—
Reply to this email directly, view it on GitHub<https://github.com/sigdat-org/sigdat/pull/20#issuecomment-1007513622>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AABHPEE74ZAW2CDN7OQKJGDUU4DOFANCNFSM5LLP2MPA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>